name: CI
on:

  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  send_messge:
     runs-on: ubuntu-latest
     steps:
        - name: send telemessage
          uses: appleboy/telegram-action@master
          with:
             to: ${{ secrets.TELEGRAM_TO }}
             token: ${{ secrets.TELEGRAM_TOKEN }}
             message: ${{ github.workflow }}  work is done!
